### ISSUE TITLE
Installation test script fails

### ISSUE THREAD

**Issue by rwfranks** [mikegrb/Net-Abuse-Utils#20]
Two issues:

(1)  AS details have changed since test script was written

(2)  Script makes use of Net::DNS resolver method which is (a) not part of published API and (b) will disappear in Net::DNS 1.05.   IMHO the test does not achieve anything useful because the null address is appended to @RESOLVERS which be used only if any others present have failed. 

[patch.zip](https://github.com/mikegrb/Net-Abuse-Utils/files/143435/patch.zip)

**Comment by mikegrb** [comment]
This makes sense, I'll get it applied and a new release cut.

**Comment by rwfranks** [comment]
On 24 February 2016 at 02:21, Rev Michael Greb <notifications@github.com>
wrote:

> This makes sense, I'll get it applied and a new release cut.
>
Excellent

Thanks

**Comment by rwfranks** [comment]
Works for me
Thanks
