### ISSUE TITLE
Installation test script fails again

### ISSUE THREAD

**Issue by rwfranks** [mikegrb/Net-Abuse-Utils#21]
The owners of AS 21844 seem to have forgotten that the planet Alderan got blown to bits.

Use the Force, Mike!

[patch.txt](https://github.com/mikegrb/Net-Abuse-Utils/files/182406/patch.txt)

**Comment by rwfranks** [comment]
AS 21844 description and company name has changed twice since previous patch!

Attached patch merely tests for existence and does not care about the content.

[patch.txt](https://github.com/mikegrb/Net-Abuse-Utils/files/224496/patch.txt)

**Comment by mikegrb** [comment]
In a858303 thank!
