### ISSUE TITLE
Breakage between release 0.23 and 0.24

### ISSUE THREAD

**Issue by NathanGibbs3** [mikegrb/Net-Abuse-Utils#22]
Something broke between release 0.23 & 0.24.
I think on commit 6e1184a46873bed11c6866126301cedfe24c619f
If I do a get_ip_country call on 43.240.136.0
Release 0.23 returns CN as it should.
Release 0.24 falls on it's face with this error.
Not a SCALAR reference at /usr/local/lib/perl5/site_perl/5.10.0/Net/Abuse/Utils.pm line 159.
or on a Debian system
Not a SCALAR reference at /usr/local/share/perl/5.20.2/Net/Abuse/Utils.pm line 159.

**Comment by mikegrb** [comment]
Thanks for reporting this and sorry for the delay in response.  This is corrected in c341ca2198a2f9bc72b280e991fe4a34ae06b8d4
